"""0010 add programs table for cfai-generated mesocycles

Adds the `programs` table that persists Mesocycle programs generated by
the cfai package (HeuristicComposer / HybridComposer). The full Mesocycle
is stored as JSONB — cfai's Pydantic schema is the source of truth on shape.

Revision ID: 0010add_programs
Revises: 0009realign_mealogs
Create Date: 2026-05-02 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # noqa: F401
import sqlmodel  # noqa: F401
from sqlalchemy.dialects import postgresql


revision: str = "0010add_programs"
down_revision: Union[str, None] = "0009realign_mealogs"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _jsonb():
    return sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql")


def upgrade() -> None:
    op.create_table(
        "programs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("macrocycle_id", sa.Uuid(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column("composer_used", sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
        sa.Column("phase", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("duration_weeks", sa.Integer(), nullable=False),
        sa.Column("sessions_per_week", sa.Integer(), nullable=False, server_default="5"),
        sa.Column("primary_focus", _jsonb(), nullable=True),
        sa.Column("spec", _jsonb(), nullable=True),
        sa.Column("athlete_snapshot", _jsonb(), nullable=True),
        sa.Column("mesocycle", _jsonb(), nullable=True),
        sa.Column("generation_metadata", _jsonb(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.ForeignKeyConstraint(["macrocycle_id"], ["macrocycles.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_programs_user_id"), "programs", ["user_id"], unique=False)
    op.create_index("idx_programs_user_created", "programs", ["user_id", "created_at"], unique=False)


def downgrade() -> None:
    op.drop_index("idx_programs_user_created", table_name="programs")
    op.drop_index(op.f("ix_programs_user_id"), table_name="programs")
    op.drop_table("programs")
